### ISSUE TITLE
jinja2.exceptions.TemplateSyntaxError

### ISSUE THREAD

**Issue by owaismultani** [mabdullahadeel/cookiecutter-django-mysql#50]
## What happened?
On running cookiecutter for the template, getting *jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '['*

* Host system configuration:
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): **Cookiecutter 2.1.1**
    * OS name and version: **Ubuntu 22.04 LTS**

      On Linux, run
      ```bash
      cookiecutter https://github.com/mabdullahadeel/cookiecutter-django-mysql.git 
      ```

    * Python version, run `python3 -V`: **Python 3.10.4**

<summary>
Logs:
<details>
<pre>
~/Projects/cookiecutter > cookiecutter https://github.com/mabdullahadeel/cookiecutter-django-mysql.git                                                                               py venv-cookiecutter 14:09:23
You've downloaded /home/asus/.cookiecutters/cookiecutter-django-mysql before. Is it okay to delete and re-download it? [yes]: 
project_name [My Awesome Project]: 
project_slug [my_awesome_project]: 
description [Behold My Awesome Project!]: 
author_name [Daniel Roy Greenfeld]: 
domain_name [example.com]: 
email [daniel-roy-greenfeld@example.com]: 
version [0.1.0]: 
Select open_source_license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 [1]: 
timezone [UTC]: 
windows [n]: 
use_pycharm [n]: 
use_docker [n]: 
Select database_engine:
1 - postgresql
2 - mysql
Choose from 1, 2 [1]: 
Select database_version:
1 - postgresql@14
2 - postgresql@13
3 - postgresql@12
4 - postgresql@11
5 - postgresql@10
6 - mysql@8.0.28
7 - mysql@8.0
8 - mysql@5.7
Choose from 1, 2, 3, 4, 5, 6, 7, 8 [1]: 
Traceback (most recent call last):
  File "/home/asus/venvs/venv-cookiecutter/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/home/asus/venvs/venv-cookiecutter/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/asus/venvs/venv-cookiecutter/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/asus/venvs/venv-cookiecutter/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/asus/venvs/venv-cookiecutter/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/asus/venvs/venv-cookiecutter/lib/python3.10/site-packages/cookiecutter/cli.py", line 194, in main
    cookiecutter(
  File "/home/asus/venvs/venv-cookiecutter/lib/python3.10/site-packages/cookiecutter/main.py", line 102, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "/home/asus/venvs/venv-cookiecutter/lib/python3.10/site-packages/cookiecutter/prompt.py", line 195, in prompt_for_config
    cookiecutter_dict[key] = render_variable(env, raw, cookiecutter_dict)
  File "/home/asus/venvs/venv-cookiecutter/lib/python3.10/site-packages/cookiecutter/prompt.py", line 160, in render_variable
    template = env.from_string(raw)
  File "/home/asus/venvs/venv-cookiecutter/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/asus/venvs/venv-cookiecutter/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/asus/venvs/venv-cookiecutter/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '['

</pre>
</details>
</summary>

**Comment by mabdullahadeel** [comment]
the fix has been released for this #53 

Thanks for reporting.
